# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: 'test/ACMESharp.MockServer.UnitTests/ACMESharp.MockServer.UnitTests.csproj -c $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: 'test/ACMESharp.UnitTests/ACMESharp.UnitTests.csproj -c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: 'ACMESharpCore.sln -c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/AcmeSharpCore-publish'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
